require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
  - 'spec/spec_helper.rb'
  - 'spec/rails_helper.rb'
  - 'spec/dummy/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false
